### ISSUE TITLE
翻译

### ISSUE THREAD

**Issue by qxy8023** [SvenZhao/var-translation#11]
引擎异常，翻译失败，请检查网络重启
{"code":"BAD_REQUEST"}
这个问题怎么破？

**Comment by SvenZhao** [comment]
@qxy8023 发了一个新版本支持谷歌和谷歌中国两个 翻译选项 常识修复了你这个问题 但是我没办法复现不知道什么情况 稍后观察一下 如果解决请关闭 如果没解决麻烦尽量多提供一些异常情况

**Comment by LinCW587** [comment]
引擎异常,翻译失败 请检查网络重启  {"name":"HTTPError","host":"translate.google.cn","hostname":"translate.google.cn","method":"GET","path":"/translate_a/single?client=t&sl=auto&tl=en&hl=en&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=%E9%AB%98%E5%BA%A6%E8%B6%B3%E5%A4%9F&tk=999465.999465","protocol":"https:","url":"https://translate.google.cn/translate_a/single?client=t&sl=auto&tl=en&hl=en&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=%E9%AB%98%E5%BA%A6%E8%B6%B3%E5%A4%9F&tk=999465.999465","gotOptions":{"path":"/translate_a/single?client=t&sl=auto&tl=en&hl=en&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=%E9%AB%98%E5%BA%A6%E8%B6%B3%E5%A4%9F&tk=999465.999465","protocol":"https:","slashes":true,"auth":null,"host":"translate.google.cn","port":null,"hostname":"translate.google.cn","hash":null,"search":"?client=t&sl=auto&tl=en&hl=en&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=%E9%AB%98%E5%BA%A6%E8%B6%B3%E5%A4%9F&tk=999465.999465","pathname":"/translate_a/single","href":"https://translate.google.cn/translate_a/single?client=t&sl=auto&tl=en&hl=en&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=%E9%AB%98%E5%BA%A6%E8%B6%B3%E5%A4%9F&tk=999465.999465","retry":{"methods":{},"statusCodes":{},"errorCodes":{}},"headers":{"user-agent":"got/9.6.0 (https://github.com/sindresorhus/got)","accept-encoding":"gzip, deflate"},"hooks":{"beforeRequest":[],"beforeRedirect":[],"beforeRetry":[],"afterResponse":[],"beforeError":[],"init":[]},"decompress":true,"throwHttpErrors":true,"followRedirect":true,"stream":false,"form":false,"json":false,"cache":false,"useElectronNet":false,"method":"GET"},"statusCode":403,"statusMessage":"Forbidden","headers":{"content-type":"text/html; charset=utf-8","cache-control":"no-cache, no-store, max-age=0, must-revalidate","pragma":"no-cache","expires":"Mon, 01 Jan 1990 00:00:00 GMT","date":"Mon, 04 Jan 2021 07:51:28 GMT","p3p":"CP=\"This is not a P3P policy! See g.co/p3phelp for more info.\"","content-security-policy":"script-src 'report-sample' 'nonce-jpIdizMjJErDUQI/tpDA+A' 'unsafe-inline';object-src 'none';base-uri 'self';report-uri /_/TranslateApiHttp/cspreport;worker-src 'self'","content-encoding":"gzip","server":"ESF","x-xss-protection":"0","x-content-type-options":"nosniff","set-cookie":["NID=206=VL65Z7CQTamY9alYianMqlo2bs1Za7Sw8Ga0KXyO06d9Fs-OUxLcogr5y1eVBIWscwjhODcvUj1kq-x5RgulUCx0VLsr3_jHITm4yAj-PH3FUAZNqqj8wMJfrInKkL4pOhLP1AM-P3g6cbMpTf_XDWOFsRBB39iaB80AhDjyUG0; expires=Tue, 06-Jul-2021 07:51:28 GMT; path=/; domain=.google.cn; HttpOnly"],"alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","connection":"close","transfer-encoding":"chunked"},"body":"<html lang=en><meta charset=utf-8><meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\"><title>Error 403 (Forbidden)!!1</title><style nonce=\"jpIdizMjJErDUQI/tpDA+A\">*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{color:#222;text-align:unset;margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px;}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}pre{white-space:pre-wrap;}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}</style><div id=\"af-error-container\"><a href=//www.google.com><span id=logo aria-label=Google></span></a><p><b>403.</b> <ins>That’s an error.</ins><p>We're sorry, but you do not have access to this page. <ins>That’s all we know.</ins></div>","code":"BAD_REQUEST"}

**Comment by SvenZhao** [comment]
@LinCW587 @qxy8023 https://marketplace.visualstudio.com/items?itemName=intellsmi.comment-translate

**Comment by LinCW587** [comment]
这个插件可以使用

**Comment by SvenZhao** [comment]
@LinCW587 我这两天把他的翻译源码抄过来

**Comment by SvenZhao** [comment]
@LinCW587 新增了一个几个渠道你测试测试

**Comment by LinCW587** [comment]
嗯,那四个渠道试了下都可以
