### ISSUE TITLE
可以支持一下中文翻译成空格分隔的单词吗？

### ISSUE THREAD

**Issue by nojsja** [SvenZhao/var-translation#12]
主要想用来替代谷歌翻译

**Comment by SvenZhao** [comment]
@nojsja 不是很明白 能给个例子吗?

**Comment by nojsja** [comment]
![image](https://user-images.githubusercontent.com/19613878/104886087-1793c180-59a4-11eb-956a-7788afa7dfe9.png)
比如说这句话的翻译，可以增加一个选项：“Please Enter The Domain Name”

**Comment by SvenZhao** [comment]
@nojsja 新版本已经支持了分词类型
