### ISSUE TITLE
最近都不能使用了 ？ 无法翻译

### ISSUE THREAD

**Issue by shen-lan** [SvenZhao/var-translation#15]
alt shift +t 无反应

**Comment by shen-lan** [comment]
可否设置多个翻译api来源 ？

**Comment by SvenZhao** [comment]
@shen-lan 
![image](https://user-images.githubusercontent.com/11209750/110468769-b4a4e800-8113-11eb-8f28-8b989e075a42.png) ke'y可以修改翻译引擎啊
