### ISSUE TITLE
希望能增加快捷键操作模式，让用户给想转换的模式设置快捷键

### ISSUE THREAD

**Issue by zhanxiaoge** [SvenZhao/var-translation#16]
可以参考插件Sort lines，插件很棒，感谢~

**Comment by SvenZhao** [comment]
@zhanxiaoge 快捷键有的win: "Alt+shift+t" 
mac": "cmd+shift+t"

**Comment by zhanxiaoge** [comment]
我希望是能给每个模式加快捷键，比如给小驼峰设置Alt+Shift+1，大驼峰设置Alt+Shift+2，Sort lines这款插件的操作方法跟你类似，但是他是支持设置多快捷键的。

**Comment by hellorayza** [comment]
> 我希望是能给每个模式加快捷键，比如给小驼峰设置Alt+Shift+1，大驼峰设置Alt+Shift+2，Sort lines这款插件的操作方法跟你类似，但是他是支持设置多快捷键的。

希望能增加配置项目，设置转换默认格式。
例如 :
```settings.json
// snakeCase | camelCase  etc ...
"var-translation.defalutFormat":"snakeCase"
```

**Comment by SvenZhao** [comment]
@zhanxiaoge  @hellorayza 新版本现在支持 指定配置各个模式的快捷键了
