### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by 296230428** [SvenZhao/var-translation#24]
最新版，vsCode 一直提示 goole 翻译失败。确定网络没问题，同时可以科学上网。

**Comment by SvenZhao** [comment]
可以切换一下翻译渠道先用 过一段时间在切换回来 这个原理是通过爬虫来搞的 有可能会被屏蔽了ip @296230428

**Comment by 296230428** [comment]
我切换了其他的，但目前只有微软的可以用，但是比较慢，能通过其他方式来处理吗，或者可以设置下翻译渠道。设置相关渠道的 api 之类的呢 我记得百度的是个人申请翻译的，好像是免费的
