### ISSUE TITLE
版本不匹配  无法安装

### ISSUE THREAD

**Issue by Rikka-S** [SvenZhao/var-translation#25]
Cannot install 'svenzhao.var-translation' extension because of version mismatch in Marketplace: validating: Cannot install 'svenzhao.var-translation' extension because of version mismatch in Marketplace

**Comment by SvenZhao** [comment]
先手动下载安装包 我也暂时搞不清楚为什么不能安装了

**Comment by Rikka-S** [comment]
直接下载也是失败的 VScode仓库中所有的版本都不能下载了  仓库那边出问题了?

**Comment by littleHiuman** [comment]
我看到vscode编辑器里的插件版本和marketplace里的插件版本不一致

**Comment by SvenZhao** [comment]
@littleHiuman 行我研究研究

**Comment by SvenZhao** [comment]
@littleHiuman @Rikka-S v0.13.32试一试
