### ISSUE TITLE
翻译失败提示链接谷歌库失败，请问如何更换支持引擎

### ISSUE THREAD

**Issue by w840980261** [SvenZhao/var-translation#34]
以前是可以翻译的，最近一直提示链接谷歌失败，看了一下readme新增了很多翻译引擎，但是没有写要怎么更换，麻烦排查一下，谢谢

**Comment by IOLOII** [comment]
me too, has see this error for some weekends

**Comment by IOLOII** [comment]
## a matter of expediency
but now you can do this for solve this problem:
> "varTranslation.translationEngine": "microsoft"

**Comment by Slowhalfframe** [comment]
在`setting.json`文件中，添加如下代码切换：
`"varTranslation.translationEngine": "baidu",`

**Comment by w840980261** [comment]
可以了，谢谢

**Comment by SvenZhao** [comment]
@w840980261 好的 后续我加上引擎切换的说明
