### ISSUE TITLE
现在使用发现，不能将中文变量翻译成英文了

### ISSUE THREAD

**Issue by SUNNERCMS** [SvenZhao/var-translation#35]
现在使用发现，不能将中文变量翻译成英文了，那就有点硬伤啦，先用翻译软件翻译，然后再转换格式 
求看

**Comment by SvenZhao** [comment]
![image](https://user-images.githubusercontent.com/11209750/136524986-e1cd7c1d-9bdc-4f2d-bcb3-133df8475b2f.png)
试着先切换一下引擎
