### ISSUE TITLE
多选时，只能转换一条内容

### ISSUE THREAD

**Issue by RanxinStart** [SvenZhao/var-translation#37]
## 基本示例
通过将多个匹配项添加到选择，此处选择了所有的concern_type
![image](https://user-images.githubusercontent.com/56920162/154902756-a964090d-bd3e-4e94-a124-73a7207f515c.png)
结果只能转换第一条
![image](https://user-images.githubusercontent.com/56920162/154902796-234dccfb-a134-44d9-9f40-03bd395709d2.png)

**Comment by SvenZhao** [comment]
@RanxinStart 这个支持的成本有点高 我这边一般没有这个使用场景   你要是能搞 要不你推个pr吧

**Comment by RanxinStart** [comment]
vscode的api好多，有空我试试。

**Comment by SvenZhao** [comment]
@RanxinStart 已更新

**Comment by hellorayza** [comment]
全选会改变原本格式
