### ISSUE TITLE
翻译无法使用，报异常，谷歌和bing都尝试了，且翻译引擎没有百度和有道

### ISSUE THREAD

**Issue by 321224148** [SvenZhao/var-translation#46]
![Snipaste_2022-04-19_20-21-08](https://user-images.githubusercontent.com/90023032/164002362-db832ee9-5285-4445-bc59-0c1dc057895e.png)

**Comment by SvenZhao** [comment]
@321224148 紧急修复了一个版本的谷歌翻译引擎 0.13.38 有问题继续看  抽时间加入自定义翻译api
