### ISSUE TITLE
中文翻译网络报错

### ISSUE THREAD

**Issue by zhibo1997** [SvenZhao/var-translation#47]
现在谷歌和bing两个选项都有问题了，如果后续能够添加自定义翻译Api就好了

**Comment by SvenZhao** [comment]
@zhibo1997 紧急修复了一个版本的谷歌翻译引擎 0.13.38 有问题继续看  抽时间加入自定义翻译api

**Comment by SvenZhao** [comment]
@zhibo1997 可以自定义翻译api了
