### ISSUE TITLE
baidu翻译异常,请检查网络或引擎token配置是否正确 {"error_code":"54000","error_msg":"PARAM_FROM_TO_OR_Q_EMPTY"}

### ISSUE THREAD

**Issue by KinBryant** [SvenZhao/var-translation#51]
![image](https://user-images.githubusercontent.com/90736717/173478133-5ec562f2-31ef-44bd-83b5-7917d62702fe.png)
是否是我没有资源包总量了？

**Comment by KinBryant** [comment]
在未选中任何文本的情况下，键入alt+shift+t，提示以上错误，是否是一个bug

**Comment by SvenZhao** [comment]
应该是吧 
![image](https://user-images.githubusercontent.com/11209750/173480920-fc3ee8bd-8767-4cb5-a197-c1206203dec4.png)
我的是标准版 高级版我也不是很清楚

**Comment by KinBryant** [comment]
收到，谢谢！

**Comment by SvenZhao** [comment]
@KinBryant 刚刚我也出现问题了.....观察观察 不知道是不是百度的问题   先用腾讯翻译君吧

**Comment by KinBryant** [comment]
收到，谢谢！
