### ISSUE TITLE
报错：baidu翻译异常

### ISSUE THREAD

**Issue by cooper1x** [SvenZhao/var-translation#53]
> baidu翻译异常,请检查网络或引擎token配置是否正确 {"error_code":"54001","error_msg":"Invalid Sign"}
<img width="511" alt="image" src="https://user-images.githubusercontent.com/9080789/186639073-c07ad586-f1c4-4a36-818d-e4b181375c2d.png">
我这边配置了appid和key，也用逗号分割了，为什么还是不行呢？
我用的是百度翻译高级版。

**Comment by SvenZhao** [comment]
@cooper1x 高级版好像没支持

**Comment by OuYang-56** [comment]
{"error_code":"54000","error_msg":"PARAM_FROM_TO_OR_Q_EMPTY"}
我是另一个情况

**Comment by SvenZhao** [comment]
@lonkang @OuYang-56 试试fork本地调试调试给个PR?  我这边复现不了

**Comment by Fluox-Etine** [comment]
baidu翻译异常,请检查网络或引擎token配置是否正确 {"error_code":"54001","error_msg":"Invalid Sign"}. 报错了

**Comment by SvenZhao** [comment]
@Fluox-Etine 试试fork本地调试调试给个PR修复一下? 我这边没有遇到

**Comment by SIX111211** [comment]
> 
什么意思
