### ISSUE TITLE
错误码54000

### ISSUE THREAD

**Issue by OuYang-56** [SvenZhao/var-translation#54]
{"error_code":"54000","error_msg":"PARAM_FROM_TO_OR_Q_EMPTY"}
填了id密钥，确认没错，但显示错误码54000 ，有什么参数空了？

**Comment by SvenZhao** [comment]
@OuYang-56  你确认一下 appid,scretkey  是不是这个格式啊?  我这边没问题 看起来网络是通的 百度那边报错了  我不好确认你的问题 能申请一个不同的key试试??
