### ISSUE TITLE
谷歌翻译地址404

### ISSUE THREAD

**Issue by elwinYe** [SvenZhao/var-translation#55]
自 2022 年 9 月 28 日起，谷歌翻译退出了中国市场，具体表现为 https://translate.google.cn/ 打开后会显示 translate.google.com.hk，不再是真正的谷歌翻译网站，这也导致划词翻译里的谷歌翻译不能正常使用了

相关链接：https://hcfy.app/blog/2022/09/28/ggg

**Comment by elwinYe** [comment]
是否可以通过更换引擎地址来修复此问题呢

**Comment by SvenZhao** [comment]
@elwinYe 好的 我看看有没有方式的修复方式

**Comment by SvenZhao** [comment]
@elwinYe 最近比较忙没时间处理   
感谢的@joesonshaw pr 已经合并了
