### ISSUE TITLE
{"error_code":"54000","error_msg":"PARAM_FROM_TO_OR_Q_EMPTY"}

### ISSUE THREAD

**Issue by SIX111211** [SvenZhao/var-translation#60]

**Comment by SIX111211** [comment]
百度 和腾讯都用了 也是按格式设置的 提示 翻译异常

**Comment by SIX111211** [comment]
![image](https://user-images.githubusercontent.com/117138262/209423470-27c38ee4-62e6-4963-b368-76efd878582d.png)

**Comment by SIX111211** [comment]
![image](https://user-images.githubusercontent.com/117138262/209423482-5d784254-f1f5-4d6c-af6d-7421d13b90ee.png)

**Comment by SIX111211** [comment]
![image](https://user-images.githubusercontent.com/117138262/209423485-ed75a2d0-e0af-4e81-84ec-b2466ddbad2d.png)

**Comment by SvenZhao** [comment]
@SIX111211 我这边不清楚你是什么情况 可以的话发邮件给我相关密钥 我调试调试

**Comment by Bobo-1125** [comment]
我百度翻译也是报54000的code，查了文档说是必填参数为空
54000 | 必填参数为空 | 请检查是否少传参数

**Comment by Bobo-1125** [comment]
> 我百度翻译也是报54000的code，查了文档说是必填参数为空 54000 | 必填参数为空 | 请检查是否少传参数

今天用着，又没问题了

**Comment by lifengsbotlp** [comment]
遇到同样的问题

**Comment by lifengsbotlp** [comment]
baidu翻译异常,请检查网络或引擎token配置是否正确 {"error_code":"54001","error_msg":"Invalid Sign"}

**Comment by Joneedhome** [comment]
同上问题，按要求填了参数
