### ISSUE TITLE
能支持自定义快捷键吗

### ISSUE THREAD

**Issue by sxynull** [SvenZhao/var-translation#62]
问题：cmd + shift + t 这个翻译快捷键 与vscode打开上一次关闭的文件 快捷键冲突
需求：能改成 cmd + option + t 或者可以自定义快捷键吗

**Comment by SvenZhao** [comment]
@sxynull  可以再vscode里面自己改啊
![image](https://user-images.githubusercontent.com/11209750/222361281-35d21e0d-aa5f-4b3b-a3ee-31a907d85cf2.png)

**Comment by sxynull** [comment]
好的 谢谢，看到了！😁
