### ISSUE TITLE
功能优化：能支持添加deepl翻译API吗

### ISSUE THREAD

**Issue by sxynull** [SvenZhao/var-translation#63]
需求：添加deepl翻译API秘钥💡，个人感觉deepl更准确😄
@SvenZhao 
<img width="615" alt="image" src="https://user-images.githubusercontent.com/32755822/224237254-6e38e6d5-89eb-4a5e-b063-fb434f18093d.png">

**Comment by SvenZhao** [comment]
@sxynull 最近没时间处理搞  代码不复杂的可以试着自己改改提个pr

**Comment by SvenZhao** [comment]
请关注一下#69

**Comment by SvenZhao** [comment]
已支持
