### ISSUE TITLE
能添加有道翻译的api么

### ISSUE THREAD

**Issue by MoLing-Dong** [SvenZhao/var-translation#66]
希望支持有道翻译，还有一个问题能不能修改自定义快捷键

**Comment by SvenZhao** [comment]
@MoLing-Dong 
翻译api的这些 我最近没事时间搞 

在键盘设置里面 修改快捷键 
![image](https://github.com/SvenZhao/var-translation/assets/11209750/10af649e-453b-407d-9af0-2c39640070e6)

**Comment by SvenZhao** [comment]
请关注一下#69

**Comment by SvenZhao** [comment]
自定义快捷键已经支持
