### ISSUE TITLE
mac中插件快捷键的问题

### ISSUE THREAD

**Issue by resolvejs** [SvenZhao/var-translation#72]
在mac中的快捷键是"cmd+shift+t"，占用了VSCODE自带的快捷键，而且无法修改插件的快捷键
![image](https://github.com/SvenZhao/var-translation/assets/46347187/75f538d7-d120-4f66-95eb-a575701d2b98)

**Comment by SvenZhao** [comment]
![image](https://github.com/SvenZhao/var-translation/assets/11209750/a03461c7-2f30-42b7-9e80-638ecb335a44)
@resolvejs 双击就可以修改了把
