### ISSUE TITLE
关于快捷键翻译的问题

### ISSUE THREAD

**Issue by suncunqian** [SvenZhao/var-translation#73]
由于在写Rust, 为"snakeCase"设置了个快捷键 "alt+s" 快捷键设置中搜索没有重复的按键

在用快捷键"alt+s"翻译时, 窗口正上方有个输入框和"网络翻译中", 就算翻译完成, 待翻译文本被翻译后的文本替代后正上方的输入框无法自动取消, 需要按下enter键, 具体图片见附件

但是相同的文本在第二次翻译时就不会出现上述情况, 中文->"alt+s"->英文很流畅.
![Snipaste_2023-11-13_13-54-58](https://github.com/SvenZhao/var-translation/assets/95872525/110132d1-a99a-4695-a73d-38b802f6ec86)

**Comment by EvATive7** [comment]
@SvenZhao 您好大佬，我也遇到了同样的情况。  
目前测试了在Python/c++/cs/js等语言下的表现情况，都如此。我认为这个问题可能和语言种类无关，而是全局性的。  
详细信息：
- 使用引擎：腾讯翻译君
- 插件版本：0.13.48
- Code版本：1.85.1

**Comment by EvATive7** [comment]
> @suncunqian @EvATive7 找到问题了 我调整一下 

大佬辛苦了

**Comment by SvenZhao** [comment]
@EvATive7 @suncunqian  fixed
