### ISSUE TITLE
能添加英文翻译成中文的选项吗

### ISSUE THREAD

**Issue by muenzhang** [SvenZhao/var-translation#74]
提供个快捷键把英文一键翻译成中文吧，保留里面的数字和_这些
还有能不能提供一个中文->英文一键翻译功能，快捷键就用alt+shift+T就行，多一个选项
写注释的时候很需要

**Comment by SvenZhao** [comment]
@muenzhang 有考虑过加一个翻译功能但是直接通过驼峰逻辑来转换的话 会打破现有的流程

**Comment by SvenZhao** [comment]
@muenzhang 新版本支持中英互译
