### ISSUE TITLE
已设置完百度的id和key，但是翻译异常

### ISSUE THREAD

**Issue by FriStd** [SvenZhao/var-translation#76]
baidu翻译异常,请检查网络或引擎token配置是否正确 {"error_code":"52003","error_msg":"UNAUTHORIZED USER"}

**Comment by FriStd** [comment]
我已经申请了id和key，个人开发者，为什么还会这样呢

**Comment by SvenZhao** [comment]
![image](https://github.co@FriStd venZhao/var-translation/assets/11209750/d8e667d2-11d7-4d4c-b39c-de8e5b3ffaf2)
@fr

**Comment by SvenZhao** [comment]
@SvenZhao 最新版会出现异常方便自己去查问题
