### ISSUE TITLE
baidu翻译异常,请检查网络或引擎token配置是否正确 {"error_code":"54000","error_msg":"PARAM_FROM_TO_OR_Q_EMPTY"}

### ISSUE THREAD

**Issue by bao-xiaoyi** [SvenZhao/var-translation#77]
baidu翻译异常,请检查网络或引擎token配置是否正确 {"error_code":"54000","error_msg":"PARAM_FROM_TO_OR_Q_EMPTY"}

**Comment by SvenZhao** [comment]
![image](https://github.com/SvenZhao/var-translation/assets/11209750/ae9e7dee-86f7-4a88-ae7f-ec686900d0ca)
@bao-xiaoyi

**Comment by Joneedhome** [comment]
我也是这个问题，appid和key都填了呀，哪里参数不对

**Comment by SvenZhao** [comment]
@SvenZhao 最新版会出现异常方便自己去查问题
