### ISSUE TITLE
可否支持 local LLMs，比如 ollama，使用模型来翻译

### ISSUE THREAD

**Issue by almensu** [SvenZhao/var-translation#78]
参考 openai-translator/openai-translator 的项目。
使用 ollama/qwen:7b 模型去做翻译
![image](https://github.com/SvenZhao/var-translation/assets/15955617/96b15c2c-6c84-4cb8-a109-ab567f28e597)

**Comment by SvenZhao** [comment]
@almensu 可以看一下代码 给个pr  个人现在没有精力处理了

**Comment by SvenZhao** [comment]
@SvenZhao 最新版可以通过chatgpt模式自定义模型
