### ISSUE TITLE
使用谷歌或者谷歌CN翻译引擎经常失败

### ISSUE THREAD

**Issue by Ryokutouto** [SvenZhao/var-translation#8]
在之前的版本中使用都正常

**Comment by LittleTurtle2333** [comment]
最近一个月都有问题，CN也只能用梯子

**Comment by LittleTurtle2333** [comment]
刚刚测了一下，开梯子都不行了

**Comment by SvenZhao** [comment]
@Ryokutouto @LittleTurtle2333 是背后的翻译api的问题 现在是不收费的免费api 我想想办法吧 看看有没有新的翻译库或者爬虫

**Comment by LittleTurtle2333** [comment]
> @Ryokutouto @LittleTurtle2333 是背后的翻译api的问题 现在是不收费的免费api 我想想办法吧 看看有没有新的翻译库或者爬虫

我用浏览器访问api没有问题。Firefox等谷歌翻译插件目前为止都可以正常使用。当然我不清楚他们的api是什么。

**Comment by SvenZhao** [comment]
@LittleTurtle2333 最近有点忙 过完元旦 抽时间 我直接用用js爬虫 重写翻译引擎把

**Comment by SvenZhao** [comment]
更换新的翻译引擎

**Comment by LittleTurtle2333** [comment]
目前完全不可翻译
![图片](https://user-images.githubusercontent.com/32336368/103348164-2ccbad80-4ad4-11eb-9166-de22e776e14d.png)


> 
> 
> 更换新的翻译引擎

**Comment by SvenZhao** [comment]
@LittleTurtle2333 稍等试试 又发了一个版本 最好重装一下插件

**Comment by LittleTurtle2333** [comment]
![image](https://user-images.githubusercontent.com/32336368/103494778-33ab4500-4e73-11eb-8dcf-c6cdb8be79ab.png)
还是一样

**Comment by LittleTurtle2333** [comment]
可以用了
