### ISSUE TITLE
微信开发者工具报错： tencent翻译异常，请检查万罗活引擎token配置是否正确{}

### ISSUE THREAD

**Issue by chenchongkang** [SvenZhao/var-translation#81]
之前都可以用的，后面手贱重新从vscode 中导入扩展就报错了，检查appId 跟秘钥都是没有错的

**Comment by SvenZhao** [comment]
@SvenZhao 最新版会出现异常方便自己去查问题

**Comment by chenchongkang** [comment]
新版在微信小程序中同一个词第一次翻译可以，第二次就报错了TypeError: Cannot read properties ofundefined (reading 'displayName”)

**Comment by SvenZhao** [comment]
@chenchongkang 最新的54版本还是稳定复现吗?

**Comment by chenchongkang** [comment]
54版本在微信开发者工具 直接报错了 Error: command 'extension.varTranslation' not found
Error: command 'extension.varTranslation' not found atg._tryExecuteCommand (D:\Program Files (x86)\Tencent\微信web开发者工具code\package,nwijsVibslvseditorbundlededitor.bundled,js:26849478) at D:\Program Files (x86)\Tencent微信web开发者工具
codelpackage,nwjsVibslvseditorbundled editor.bundled,js:26849359
