### ISSUE TITLE
关于docker容器的适配性

### ISSUE THREAD

**Issue by Ebbjik** [SvenZhao/var-translation#82]
像我这么干的人应该少，就是我本身使用win开发，然后嫌环境配置麻烦，就装了docker，用vscode连接容器进行开发，不止这个插件，我试了好多，都出现了在宿主机上可以使用，但是在容器中无法使用
具体报错如下

**Comment by Ebbjik** [comment]
![Snipaste_2024-08-16_02-00-45](https://github.com/user-attachments/assets/e82c7159-4272-4f63-a65b-42ffad2e316c)

**Comment by SvenZhao** [comment]
@Ebbjik 这个可能和容器的网络权限有关系 我这边远程没遇到

**Comment by Ebbjik** [comment]
你是对的，我是笨蛋，容器随便进行一个端口映射这个问题就解决了
